"""
Automatically generated by Colab.

Gabriella Braz - 10402554  
Giovana Liao - 10402264  
Maria Julia de Pádua - 10400630

Original file is located at
    https://colab.research.google.com/drive/1lBT3Zat4MPqG5Rh_mjBWcv85Ztz2CP2D

#Limiarização Adaptativa

## Instalação de bibliotecas
"""

# pip install opencv-python matplotlib numpy pillow

"""##Pré Processamento da Imagem"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import urllib.request

# 1. Baixa a imagem da internet
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_2.jpg/640px-Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_2.jpg"
resposta = urllib.request.urlopen(url)
imagem_bytes = bytearray(resposta.read())
imagem_array = np.asarray(imagem_bytes, dtype=np.uint8)
imagem = cv2.imdecode(imagem_array, cv2.IMREAD_COLOR)

# 2. Converte para escala de cinza
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

# 3. Aplica desfoque gaussiano
imagem_borrada = cv2.GaussianBlur(imagem_cinza, (5, 5), 0)

# 4. Limiarização simples (global)
_, limiar_global = cv2.threshold(imagem_borrada, 127, 255, cv2.THRESH_BINARY_INV)

# 5. Limiarização adaptativa - MÉDIA
thresh_media = cv2.adaptiveThreshold(
    imagem_borrada, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY_INV, 11, 4
)

# 6. Limiarização adaptativa - GAUSSIANA
thresh_gauss = cv2.adaptiveThreshold(
    imagem_borrada, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 4
)

# 7. Mostra as imagens lado a lado
fig, axs = plt.subplots(1, 5, figsize=(22, 5))

axs[0].imshow(cv2.cvtColor(imagem, cv2.COLOR_BGR2RGB))
axs[0].set_title("Imagem Original")
axs[0].axis("off")

axs[1].imshow(imagem_cinza, cmap="gray")
axs[1].set_title("Imagem em Tons de Cinza")
axs[1].axis("off")

axs[2].imshow(limiar_global, cmap="gray")
axs[2].set_title("Limiarização Global")
axs[2].axis("off")

axs[3].imshow(thresh_media, cmap="gray")
axs[3].set_title("Adaptativa - Média")
axs[3].axis("off")

axs[4].imshow(thresh_gauss, cmap="gray")
axs[4].set_title("Adaptativa - Gaussiana")
axs[4].axis("off")

plt.tight_layout()
plt.show()
